# Generated by Django 5.1.4 on 2025-01-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="user_id",
            new_name="user",
        ),
    ]
