# Generated by Django 5.1.4 on 2025-01-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_id_teacher_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parent",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="user_id",
            new_name="user",
        ),
    ]
