# Generated by Django 5.1.4 on 2025-01-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_id_parent_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.class"
            ),
        ),
    ]
