# Generated by Django 5.1.5 on 2025-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_shopitem_date_created"),
        ("users", "0007_alter_student_blood_group_alter_student_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="purchases",
            field=models.ManyToManyField(to="main.shopitempurchase"),
        ),
    ]
