# Generated by Django 5.1.5 on 2025-01-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_rename_shopitempurchase_purchase"),
        ("users", "0009_remove_userprofile_purchases"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_border",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.shopitem",
            ),
        ),
    ]
