# Generated by Django 5.1.5 on 2025-01-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userprofile_profile_border"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="completed_challenge_questions",
        ),
        migrations.RemoveField(
            model_name="student",
            name="completed_quiz_questions",
        ),
        migrations.RemoveField(
            model_name="student",
            name="correct_challenge_questions",
        ),
        migrations.RemoveField(
            model_name="student",
            name="correct_quiz_questions",
        ),
    ]
