# Generated by Django 5.1.4 on 2025-01-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendence",
            name="days_attended",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[("Weekly", "Weekly"), ("Daily", "Daily")], max_length=50
            ),
        ),
    ]
