# Generated by Django 5.1.4 on 2025-01-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="grade",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="quiz",
            name="grade",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="correct",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="question",
            field=models.TextField(max_length=150),
        ),
    ]
