# Generated by Django 5.1.4 on 2025-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_challenge_grade_quiz_grade_alter_quiz_correct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="monthly_challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField(default=4)),
                ("question", models.TextField(max_length=400)),
                ("answer", models.CharField(max_length=100)),
            ],
        ),
    ]
