# Generated by Django 5.1.4 on 2025-01-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_attendence_days_attended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="correct",
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
