# Generated by Django 5.1.4 on 2025-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_quiz_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("daily", "Daily")], max_length=50
            ),
        ),
    ]
