# Generated by Django 5.1.4 on 2025-01-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_challenge_challenge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("daily", "Daily")],
                default="daily",
                max_length=50,
            ),
        ),
    ]
