# Generated by Django 5.1.4 on 2025-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="unit",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
