# Generated by Django 5.1.5 on 2025-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_challengescompleted"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChallengesCompleted",
        ),
    ]
