# Generated by Django 5.1.5 on 2025-01-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_delete_challengescompleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.challenge",
            ),
        ),
    ]
