# Generated by Django 5.1.5 on 2025-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_challengetracker_quiztracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengetracker",
            name="completed_questions",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="main.question"
            ),
        ),
    ]
