# Generated by Django 5.1.5 on 2025-01-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_completed_questions_challengetracker_correct_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengetracker",
            name="incorrect_questions",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by_incorrect", to="main.question"
            ),
        ),
        migrations.AlterField(
            model_name="challengetracker",
            name="correct_questions",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by_correct", to="main.question"
            ),
        ),
    ]
