# Generated by Django 5.1.5 on 2025-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_challengetracker_incorrect_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengetracker",
            name="answer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
