# Generated by Django 5.1.5 on 2025-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_challenge_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                blank=True,
                choices=[("weekly", "Weekly"), ("daily", "Daily")],
                default="daily",
                max_length=50,
                null=True,
            ),
        ),
    ]
