# Generated by Django 5.1.5 on 2025-01-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_question_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengetracker",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.question",
            ),
        ),
    ]
