# Generated by Django 5.1.5 on 2025-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_shopitem_shopitempurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="item_type",
            field=models.CharField(
                choices=[("avatar_border", "Avatar Border"), ("avatar", "Avatar")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="shopitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
