# Generated by Django 5.1.5 on 2025-01-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_shopitem_date_created"),
        ("users", "0008_userprofile_purchases"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopItemPurchase",
            new_name="Purchase",
        ),
    ]
