# Generated by Django 5.1.5 on 2025-01-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_attendance_delete_attendence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="status",
        ),
        migrations.AddField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=False),
        ),
    ]
