# Generated by Django 5.1.5 on 2025-01-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_remove_attendance_status_attendance_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="days_attended",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="days_passed",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
