# Generated by Django 5.1.5 on 2025-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_remove_attendance_days_attended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
